const CartActionType = {

    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    UPDATE_CART: "UPDATE_CART",
    UPDATE_CART_COUNT: "UPDATE_CART_COUNT",
    LOAD_CURRENCIES: "LOAD_CURRENCIES",
    CHANGE_CURRENCY: "CHANGE_CURRENCY",

}

export default CartActionType