const CategoryActionType = {

    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    GET_NAV_CATEGORIES: "GET_NAV_CATEGORIES",
    SET_ROUTE: "SET_ROUTE",
    GET_PRIDUCT_LIST: "GET_PRIDUCT_DISCRIPTION",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    RELEASE_SELECTED_PRODUCT: "RELEASE_SELECTED_PRODUCT"

}

export default CategoryActionType