const CategoryActionType = {

    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    GET_NAV_CATEGORIES: "GET_NAV_CATEGORIES",
    GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",

}

export default CategoryActionType