const CategoryActionType = {

    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    GET_NAV_CATEGORIES: "GET_NAV_CATEGORIES",
    GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
    SET_ROUTE: "SET_ROUTE",
    GET_PRIDUCT_DISCRIPTION: "GET_PRIDUCT_DISCRIPTION",
    GET_PRIDUCT_LIST: "GET_PRIDUCT_DISCRIPTION",

}

export default CategoryActionType